#!/usr/bin/env bash

pkg install $(cat apt) -y &&
stow -vt ~/ home &&
stow -vt ~/.config config &&
sh scripts/curl.sh &&
cat scripts/shortcuts | ./scripts/profileshortcuts.awk &&
cat scripts/shortcuts | ./scripts/rangershortcuts.awk &&
source ~/.profile
